services:
  claude-proxy:
    image: node:22-alpine
    working_dir: /app
    command: node server/server.js
    ports:
      - "42069:42069"
    volumes:
      - ~/.claude:/root/.claude
      - ./server:/app/server
      - ./util:/app/util

